### ISSUE TITLE
Plugin search on website doesn't work

### ISSUE THREAD

**Issue by ad-on-is** [gulpjs/plugins#188] opened 2015-05-20 09:38 UTC
When I go to: http://gulpjs.com/plugins/ there is nothing there. Only the searchbar and the orange body background. Also if I start typing some text or hit enter, still nothing happens.

OS X Yosemite 10.10.3
Tried in Chrome, Firefox, Safari

**Comment by contra** [comment] 2015-05-20 21:39
duplicate of #182 i dont have time to maintain it, im going to redirect it to npm this week and shut it down unless somebody else wants to take ownership

**Closed by contra** 2015-05-20 21:39 UTC
